### ISSUE TITLE
Setup appveyor

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-latexml#1]
@ronaldtse please add project to appveyor and give me a link to build status icon

**Comment by CAMOBAP** [comment]
@ronaldtse also could you please review/approve legal information in https://github.com/riboseinc/chocolatey-latexml/blob/master/latexml.nuspec

**Comment by ronaldtse** [comment]
AppVeyor approved. Please wait for me on legal information. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse thanks, issues to fix on my side

 - [x] 'kpsewhich' is not recognized as an internal or external command,
 - [x] Warning: Do not use dmake.exe utility as it is no longer part of Strawberry Perl, use gmake.exe instead!
 - [x] > Warning (mostly harmless): No library found for -lxml2
Warning (mostly harmless): No library found for -lzlib
Warning (mostly harmless): No library found for -lmoldname
Warning (mostly harmless): No library found for -lkernel32
Warning (mostly harmless): No library found for -luser32
Warning (mostly harmless): No library found for -lgdi32
Warning (mostly harmless): No library found for -lwinspool
Warning (mostly harmless): No library found for -lcomdlg32
Warning (mostly harmless): No library found for -ladvapi32
Warning (mostly harmless): No library found for -lshell32
Warning (mostly harmless): No library found for -lole32
Warning (mostly harmless): No library found for -loleaut32
Warning (mostly harmless): No library found for -lnetapi32
Warning (mostly harmless): No library found for -luuid
Warning (mostly harmless): No library found for -lws2_32
Warning (mostly harmless): No library found for -lmpr
Warning (mostly harmless): No library found for -lwinmm
Warning (mostly harmless): No library found for -lversion
Warning (mostly harmless): No library found for -lodbc32
Warning (mostly harmless): No library found for -lodbccp32
Warning (mostly harmless): No library found for -lcomctl32

**Comment by ronaldtse** [comment]
Regarding `kpsewhich`, are you calling the `latexmlmath` command?

**Comment by CAMOBAP** [comment]
@ronaldtse nope all of them happens during installation, so latexml even not installed

**Comment by ronaldtse** [comment]
As shown on https://dlmf.nist.gov/LaTeXML/get.html , there are prerequisites for Windows:

> Installing prebuilt There is currently no prebuilt LaTeXML for Windows, but it should install cleanly under Strawberry Perl’s CPAN. Install the TeX-system of your choice (if desired), ImageMagick (see > Installing ImageMagick under Windows) and then install LaTeXML using:
> `cpan LaTeXML`
> Installing the optional package Image::Magick on Windows seems to be problematic, so we have omitted it from these instructions. You may want to try , but you’re on your own, there! You may have better luck with Graphics::Magick.

On Chocolatey I noticed that they have MiKTeX. So maybe we need to install MiKTeX (https://chocolatey.org/packages/miktex) as a dependency for LaTeXML.

**Comment by CAMOBAP** [comment]
> but it should install cleanly under Strawberry Perl’s CPAN

Yep I use Strawberry Perl too, also I use `cpanm` for dependency resolution

> So maybe we need to install MiKTeX

Maybe but I'm not sure, they [definitely can work together](https://github.com/brucemiller/LaTeXML/wiki/Integrating-LaTeXML-into-TeX-editors), but I'm not sure which way is right.

LaTeXML by itself don't create any requirements for TeX environment

**Comment by ronaldtse** [comment]
@CAMOBAP795 Indeed. However `kpsewhich` is installed by the TeX environment. I suspect that LaTeXML wants to read the `.sty` files from the TeX distribution?

In any case, we can also post an issue in https://github.com/brucemiller/LaTeXML .

**Comment by CAMOBAP** [comment]
> However `kpsewhich` is installed by the TeX environment.

Thanks for note, this is new info for me, let me check

**Comment by CAMOBAP** [comment]
What I have found in chocolatey repo for `https://chocolatey.org/packages?q=*TeX*` (sorted according to downloads count):
 - https://chocolatey.org/packages/miktex - not like it because installer ~ 200Mb
 - https://chocolatey.org/packages/texmaker - 62Mb
 - https://chocolatey.org/packages/texstudio - 74Mb
 - https://chocolatey.org/packages/lyx - ~58 MB

I will start Lyx first because of size

**Comment by ronaldtse** [comment]
I feel that Lyx depends on another distribution? If not, then it's great!

**Comment by ronaldtse** [comment]
Ha... it depends on MiKTeX!

**Comment by CAMOBAP** [comment]
@ronaldtse Oh NOOOO(

I will check transitive dependencies next time)

**Comment by ronaldtse** [comment]
TeXStudio:
> If you want to use MiKTeX make sure to install it before TeXstudio! Unless you don't want to compile documents or you know what you do, you will need MiKTeX.

TeXMaker has a red-light.

**Comment by ronaldtse** [comment]
But maybe TeXMaker works. Otherwise, back to MiKTeX...

**Comment by CAMOBAP** [comment]
Moving to `MiKTeX`, for lyx first issue gone, so for `MiKTeX` it should be the same, moving to next issue

**Comment by CAMOBAP** [comment]
Ok what I have found for now:
 - on appveyor there is preinstalled perl
 - StrawberryPerl interferes with preinstalled perl
 - If I use pre-installed perl it have a problem with missing libxml

Now I need a way to `activate` StrawberryPerl and use it, working on this

**Comment by ronaldtse** [comment]
@CAMOBAP795 this AppVeyor file uses Strawberry Perl: https://github.com/conan-community/conan-strawberryperl/blob/release/5.28.1.1/appveyor.yml

With Chocolatey:
https://www.intermediateperl.com/2017/05/automated-testing-on-windows-with-appveyor/

**Comment by CAMOBAP** [comment]
> this AppVeyor file uses Strawberry Perl: https://github.com/conan-community/conan-strawberryperl/blob/release/5.28.1.1/appveyor.yml

We have nothing to do with [conan c++ native manager](https://github.com/conan-io/conan)

> https://www.intermediateperl.com/2017/05/automated-testing-on-windows-with-appveyor/

Exactly I used this approach yesterday, the only problem which I have for now is:
 - `'kpsewhich: warning: running with administrator privileges'`

And tests failed, I tried to run as non administrator with `C:\Tools\PsTools\psexec.exe` it doesn't work yet so I will continue research why

Also we can skip test but I think this isn't right way...

**Comment by ronaldtse** [comment]
Got it. Is `kpsewhich` not being provided by MiKTeX?

**Comment by CAMOBAP** [comment]
@ronaldtse nope it exists there, but because if appveyor (it run CI steps as administrator user) we got extra line in output, and unit tests failed because of this

I'm looking for a way to run without admin privilege

**Comment by CAMOBAP** [comment]
New problem (I hope last one)

```
Can't locate loadable object for module XML::LibXML in @INC (@INC contains: C:/Strawberry/perl/site/bin/../lib C:/Perl/site/lib C:/Perl/lib .) at C:/Strawberry/perl/site/bin/../lib/XML/LibXML.pm line 156.
BEGIN failed--compilation aborted at C:/Strawberry/perl/site/bin/../lib/XML/LibXML.pm line 156.
Compilation failed in require at C:/Strawberry/perl/site/bin/../lib/LaTeXML/Common/Object.pm line 16.
BEGIN failed--compilation aborted at C:/Strawberry/perl/site/bin/../lib/LaTeXML/Common/Object.pm line 16.
Compilation failed in require at C:/Strawberry/perl/site/bin/../lib/LaTeXML/Common/Error.pm line 16.
BEGIN failed--compilation aborted at C:/Strawberry/perl/site/bin/../lib/LaTeXML/Common/Error.pm line 16.
Compilation failed in require at C:/Strawberry/perl/site/bin/../lib/LaTeXML/Core.pm line 18.
BEGIN failed--compilation aborted at C:/Strawberry/perl/site/bin/../lib/LaTeXML/Core.pm line 18.
Compilation failed in require at C:\Strawberry\perl\site\bin\latexml line 20.
BEGIN failed--compilation aborted at C:\Strawberry\perl\site\bin\latexml line 20.
Command exited with code 1
Push-AppveyorArtifact C:\ProgramData\chocolatey\logs\chocolatey.log
Uploading artifact chocolatey.log (1,701,746 bytes)...100%
```

**Comment by CAMOBAP** [comment]
Fixed

@ronaldtse let me summarize rest tasks:
 - [x] give me project id or build badge URL
 - [x] can I reuse the same `CHOCO_API_KEY` for `chocolatey-latexml`
 - [x] confirm legal info in `latexml.nuspec`
 - [x] check if `test.tex` good enough

**Comment by ronaldtse** [comment]
Badges:

```
Project status badge

Current status

SVG image URL
https://ci.appveyor.com/api/projects/status/evanr46yj1t4l9fe?svg=true
Raster image URL
https://ci.appveyor.com/api/projects/status/evanr46yj1t4l9fe
Sample markdown code
[![Build status](https://ci.appveyor.com/api/projects/status/evanr46yj1t4l9fe?svg=true)](https://ci.appveyor.com/project/ribose/chocolatey-latexml)
master branch status badge

SVG branch image URL
https://ci.appveyor.com/api/projects/status/evanr46yj1t4l9fe/branch/master?svg=true
Raster branch image URL
https://ci.appveyor.com/api/projects/status/evanr46yj1t4l9fe/branch/master
Branch sample markdown code
[![Build status](https://ci.appveyor.com/api/projects/status/evanr46yj1t4l9fe/branch/master?svg=true)](https://ci.appveyor.com/project/ribose/chocolatey-latexml/branch/master)
```

**Comment by CAMOBAP** [comment]
@ronaldtse will we use the same chocolatey account (token) for distribution?

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes, let's do this for now. We might have to change it later.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks let me know if `latexml.nuspec` and `test.tex` are ok

Also important thing (I faced with this on appveyor) if there is many perl installations on target machine we need to explicitly use `Strawberry Perl`, like this: 
 - `cmd.exe /c "set PATH=C:\Strawberry\perl\bin;%PATH% & C:\Strawberry\perl\site\bin\latexml --VERSION"`

cc @opoudjis

**Comment by ronaldtse** [comment]
@CAMOBAP795 the nuspec `copyright` should write "Public Domain" (as shown on https://dlmf.nist.gov/LaTeXML/notices.html). Other than it's OK for now.

For `text.tex`, we should not have to escape the backslashes?

**Comment by CAMOBAP** [comment]
@ronaldtse IDK, I have found this example somewhere here https://github.com/brucemiller/LaTeXML/tree/master/t

**Comment by ronaldtse** [comment]
I think the text.tex was given by @opoudjis , which was given by me from OGC?

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for remind, I will use this one https://github.com/riboseinc/metanorma-ogc/issues/21#issuecomment-463653232

**Comment by CAMOBAP** [comment]
@ronaldtse done, if you are ok, we are ready to release

**Comment by ronaldtse** [comment]
Please proceed. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse done https://chocolatey.org/packages/latexml

**Comment by CAMOBAP** [comment]
There is rule violation in our package https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotContainChocoCommands

We use choco install to do a workaround during miktex installation (to point correct version of Perl)

**Comment by ronaldtse** [comment]
Can we specify the path of Strawberry Perl prior to the installation of LaTeXML?

**Comment by CAMOBAP** [comment]
@ronaldtse I did this by using choco command, but as you may see in link above it's not allowed, looking for another solution

**Comment by ronaldtse** [comment]
@CAMOBAP795 so LaTeXML doesn't require any TeX distribution -- let's get rid of MiKTeX dependency.

**Comment by CAMOBAP** [comment]
@ronaldtse you absolutely right, sorry I forgot to tell that I already did this

And we are waiting for reivew now https://chocolatey.org/packages/latexml

**Comment by CAMOBAP** [comment]
Done
