### ISSUE TITLE
remote: Permission to metanorma/chocolatey-latexml.git denied to metanorma-ci.

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-latexml#15]
https://github.com/metanorma/chocolatey-latexml/runs/4209433199?check_suite_focus=true

@ronaldtse could you please doublecheck `METANORMA_CI_PAT_TOKEN` permissions for this repo

P.S. also could you please rename default branch `master -> main` from settings

**Comment by ronaldtse** [comment]
Branch renamed. 

metanorma-ci user now has write access to this repo.
