### ISSUE TITLE
iconUrl need to point to CDN

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-latexml#18]
Currently, we use https://dlmf.nist.gov/LaTeXML/x7.png

Per review comment:

> For the next package version can you please host the icon on your package sources and link to it via a CDN: https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines

@ronaldtse do you have any idea how to accomplish this, maybe already use some CDN where we can put this icon?

**Comment by ronaldtse** [comment]
I think it just means we should copy the logo to the chocolatey package file in our GitHub, then use https://statically.io/convert/ to get a CDN link.

**Comment by CAMOBAP** [comment]
Sounds like a solution, thanks

**Comment by ronaldtse** [comment]
FYI Statically was mentioned by the guidelines 😉

**Comment by CAMOBAP** [comment]
@ronaldtse that's true I just couldn't me believe that it's free) (I never used such tools before)

DOne

**Comment by ronaldtse** [comment]
👍
