### ISSUE TITLE
The command to call LaTeXML in PowerShell is not recognized

### ISSUE THREAD

**Issue by rhsecops** [metanorma/chocolatey-latexml#19]
Hello, I posted the issue at https://github.com/brucemiller/LaTeXML/issues/1853 and the developer referenced me to you.

In short the problem is that chocolatey says that the install was successful but the command is still not recognized.

**Comment by ronaldtse** [comment]
Thank you @ToastDoggo for reporting this!

@CAMOBAP could you help investigate to see what's going on?

**Comment by CAMOBAP** [comment]
Probably Environment variables need to be refreshed, this can be achieved in several ways:
 - Execute `Update-SessionEnvironment` command in powershell or `refreshenv` for batch
 - Open new PowerShell window

@ToastDoggo could you please try something from the list above?

**Comment by ronaldtse** [comment]
@ToastDoggo could you help check whether it works after refreshing the environment or using a new shell window? Thanks!

(FYI @brucemiller @dginev)

**Comment by rhsecops** [comment]
> 

I'm so sorry for the late reply. The first command on PowerShell isn't recognised:
![image](https://user-images.githubusercontent.com/94985056/172566874-873347c6-e0d3-444b-9b66-92c8c433e2a0.png)

The command for CMD works but still latexml isn't working.

**Comment by CAMOBAP** [comment]
Looks like some issues with chocolatey installation, which version of chocolatey is installed?
Maybe it should be upgraded `choco upgrade chocolatey`

**Comment by rhsecops** [comment]
I just upgraded it as you told me and tried to reinstall LaTeXML with the flags `--failonstderr --force reinstall` and now it tells me this:
![image](https://user-images.githubusercontent.com/94985056/173052455-ecf706cb-a176-4b7b-a099-66faa4da1bf7.png)

This is what I have when I list sources:
![image](https://user-images.githubusercontent.com/94985056/173053277-6f75a03c-bcfa-4379-88b0-e8a7e39bdad2.png)

**Comment by CAMOBAP** [comment]
@ToastDoggo sorry for ignore, maybe debug logs left on your machine ".\cpanm\work\*\build.log", could you please attach it?

**Comment by CAMOBAP** [comment]
Feel free to reopen if it still valid
