### ISSUE TITLE
update to 0.8.8

### ISSUE THREAD

**Issue by xworld21** [metanorma/chocolatey-latexml#20]
Chocolatey is still carrying version 0.8.5 of LaTeXML, would you be able to update it to 0.8.8?

**Comment by ronaldtse** [comment]
@CAMOBAP can you please help here? Thanks!

**Comment by CAMOBAP** [comment]
The 0.8.8 the same as 0.8.5 for some reason failed automated test pass

https://gist.github.com/choco-bot/63d66178d0db53ca19ce41b7e3b21ed7
https://gist.github.com/choco-bot/5764fbf983b48f2e4ab85042d2f2a8e7

Communicating with choco's support right now

**Comment by CAMOBAP** [comment]
https://community.chocolatey.org/packages/latexml/0.8.8 all test passed waiting for approvement

**Comment by CAMOBAP** [comment]
Approved
