### ISSUE TITLE
Track LaTeXML tests on Windows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-latexml#6]
@dginev is currently addressing the problems we ran into here: https://github.com/brucemiller/LaTeXML/pull/1109

* Failing comparisons due to `kpsewhich: warning: running with administrator privileges’
* A failing test with MiKTeX

Once that is merged/released we probably need an update.

**Comment by CAMOBAP** [comment]
@ronaldtse just to be on the same page, for us it may affect only in case if strawberryperl + miktex preinstalled, we don't plan to add miktex dependency back, right?

**Comment by ronaldtse** [comment]
@CAMOBAP795 no, we don't plan to add MiKTeX dependency back, but I wonder if it is useful for others. Does Chocolatey allow optional dependencies?

**Comment by CAMOBAP** [comment]
> Does Chocolatey allow optional dependencies?

@ronaldtse Unfortunately not yet https://stackoverflow.com/questions/27756319/optional-dependencies-in-chocolatey-package

But In my opinion we should not follow this way, if user will need MiKTeX he will just install it with single `cinst` command, In my opinion there is no reason to create/maintain package specially for this

**Comment by ronaldtse** [comment]
That’s true. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse tests enabled, I think we can close this one

**Comment by ronaldtse** [comment]
Thanks!
