### ISSUE TITLE
Remove dependency of MiKTeX

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-latexml#7]
As described by @dginev here https://chocolatey.org/packages/miktex#comment-4420594892 , the Chocolatey MiKTeX installation binary changes location (path) on every release. There is a large time gap between "MiKTeX release" and "Chocolatey MiKTeX package release", which renders our package unusable (unable to install MiKTeX).

While there is TeXLive on Windows, their Chocolatey package is severely outdated (from 2012) and unusable.

From discussions we have decided to remove the dependency of the TeX system from this package, since LaTeXML can function without it. The user can choose whatever TeX distribution they want and have to install manually.

Ref:

From @brucemiller:
> For Windows & Chocolatey, maybe that latter approach
> makes the most sense for LaTeXML itself --- omit the
> dependency and let the users install what they like,
> even outside of Chocolatey.

From me:
> I think this might be the best choice. Let the user decide their own setup. What we could do is to test Chocolatey LaTeXML under both cases: if a TeX distribution is or is not present.

This task is to :
1. Remove dependency of MiKTeX from the package
2. Update AppVeyor tests to install a TeX distribution automatically (and share this AppVeyor with https://github.com/brucemiller/LaTeXML/pull/1109#issuecomment-482701612 )

**Comment by CAMOBAP** [comment]
@ronaldtse We already have no miktex https://chocolatey.org/packages/latexml

Reading TeX installation, which exactly tests need to be added?

**Comment by ronaldtse** [comment]
When we do AppVeyor do we install MiKTeX then?

With TeX installation we want to be sure LaTeXML can read the installed styles, eg. Run a sample that uses `amsmath`.

**Comment by CAMOBAP** [comment]
> When we do AppVeyor do we install MiKTeX then?

At this moment we don't install any TeX and use LaTeXML as standalone only https://github.com/metanorma/chocolatey-latexml/blob/master/appveyor.yml

> With TeX installation we want to be sure LaTeXML can read the installed styles, eg. Run a sample that uses `amsmath`.

According to tests in `metanorma-standoc`, command `latexmlmath --preload=amsmath  -- -` works properly, I can add similar test to this repo

@ronaldtse make sense?

**Comment by ronaldtse** [comment]
Oh... I totally forgot amsmath is already supported. What are the common math styles that people use? Let me find out...

**Comment by ronaldtse** [comment]
According to https://github.com/metanorma/metanorma.com/issues/83 , only these packages in LaTeXML depend on external TeX distribution.

```
color.sty
colordvi.sty
ntheorem.sty
pgfkeys.code
pgfmath.code
siunitx.sty
tikz.sty
xcolor.sty
```

So the test for testing integration with MiKTeX could use any of these packages, such as `ntheorem` or `color`.

For `xcolor`, @dginev says:
> Currently latexml won't stop you from using a package that *may* require a tex distribution, since in some cases you skirt away from the dependency. For instance xcolor only requires the tex distribution if you use the extended option set, but would be OK without one if you just load it with no options.
