### ISSUE TITLE
Add Chocolatey LaTeXML test when MiKTeX is installed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-latexml#8]
According to https://github.com/metanorma/metanorma.com/issues/83 , these packages in LaTeXML depend on external TeX distribution.

```
color.sty
colordvi.sty
ntheorem.sty
pgfkeys.code
pgfmath.code
siunitx.sty
tikz.sty
xcolor.sty
```

So the test for testing integration with MiKTeX could use any of these packages, such as `ntheorem` or `color`.

For `xcolor`, @dginev says:
> Currently latexml won't stop you from using a package that *may* require a tex distribution, since in some cases you skirt away from the dependency. For instance xcolor only requires the tex distribution if you use the extended option set, but would be OK without one if you just load it with no options.

_Originally posted by @ronaldtse in https://github.com/metanorma/chocolatey-latexml/issues/7#issuecomment-488255590_

**Comment by CAMOBAP** [comment]
@ronaldtse anything else need to be done in the scope of this ticket?

**Comment by ronaldtse** [comment]
Yes, as described above:

> So the test for testing integration with MiKTeX could use any of these packages, such as `ntheorem` or `color`.

You need to add a test that uses `ntheorem` and `color` that:
* will fail if MiKTeX isn't installed;
* will pass if MiKTeX is installed.

**Comment by CAMOBAP** [comment]
@ronaldtse can you give me a clue what a test there should be, should I just call `latexmlc` against some files which use `ntheorem` or `color`?

**Comment by ronaldtse** [comment]
Yes, such as these examples (just 1 tex file for each package is enough):

https://www.dickimaw-books.com/latex/thesis/html/ntheorem.html

https://en.wikibooks.org/wiki/LaTeX/Colors

**Comment by CAMOBAP** [comment]
@ronaldtse tests added

**Comment by CAMOBAP** [comment]
I just have checked that this already [done in the original latexml project](https://github.com/brucemiller/LaTeXML/blob/master/.appveyor.yml#L6).

They have a matrix with `bare` (no tex installation) and `miktex`

So I'm not sure that we need to do this at all.

@ronaldtse let me know what you think about this, should we still proceed?

**Comment by ronaldtse** [comment]
Well, that’s great. Then we don’t need to do this. Thanks @dnigev !
